### PR TITLE
Fixes Phaser v2.6.1 issue

### PR DESCRIPTION
**Pull request by SamHession**
Changes the baseTextureCache variable to baseTexture, fixing an issue found with Phaser version 2.6.1

### CODE REVIEW

**Comment by koraysels** [comment]
can this be merged ? I have this issue tooo

**Comment by netcell** [comment]
Hi @SamHession and @koraysels,

I am not currently using Phaser, can you guys confirm that this version works? I will merge and edit README afterward.

**Comment by koraysels** [comment]
For me it works with the laters phaser release. Also maybe consider publishing your work to npm? :D

On 24 Sep 2016, at 02:57, Nguyễn Tuấn Anh notifications@github.com wrote:

Hi @SamHession and @koraysels,

I am not currently using Phaser, can you guys confirm that this version works? I will merge and edit README afterward.

**Comment by netcell** [comment]
I'm not happy with the current implementation, and I strongly recommend you not using it so no I am not publishing it on npm :)

**Pull request merged**
